// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzYz4x9YRUvkFBWd-X5zdoYXnm3INjiw',
    appId: '1:533911091480:web:99c184451212791b31866d',
    messagingSenderId: '533911091480',
    projectId: 'cliniq-core',
    authDomain: 'cliniq-core.firebaseapp.com',
    storageBucket: 'cliniq-core.firebasestorage.app',
    measurementId: 'G-P61EF0VTKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXS-eSHSdrerapkk0OfUSMpSLfhBhc2Is',
    appId: '1:533911091480:android:7929d784dfc8f6f131866d',
    messagingSenderId: '533911091480',
    projectId: 'cliniq-core',
    storageBucket: 'cliniq-core.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMTxNXFhSbYaNF06L4qvPi5uQRHafPOk',
    appId: '1:533911091480:ios:9fa7f16b440d1d6a31866d',
    messagingSenderId: '533911091480',
    projectId: 'cliniq-core',
    storageBucket: 'cliniq-core.firebasestorage.app',
    iosBundleId: 'com.example.cliniqCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwMTxNXFhSbYaNF06L4qvPi5uQRHafPOk',
    appId: '1:533911091480:ios:9fa7f16b440d1d6a31866d',
    messagingSenderId: '533911091480',
    projectId: 'cliniq-core',
    storageBucket: 'cliniq-core.firebasestorage.app',
    iosBundleId: 'com.example.cliniqCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSzYz4x9YRUvkFBWd-X5zdoYXnm3INjiw',
    appId: '1:533911091480:web:34e6aea9f62a0b7431866d',
    messagingSenderId: '533911091480',
    projectId: 'cliniq-core',
    authDomain: 'cliniq-core.firebaseapp.com',
    storageBucket: 'cliniq-core.firebasestorage.app',
    measurementId: 'G-48KBS6VSRX',
  );
}
